---

- name: Prepare directory
  shell: |
    mkdir -p {{ dir }}

- name: download golang tar
  get_url:
    url: "https://storage.googleapis.com/golang/go{{go_version}}.linux-amd64.tar.gz"
    dest: "{{dir}}"
    mode: 0440
    validate_certs: no

- name: Remove old installation of Go
  file:
    path: /usr/local/go
    state: absent
  become: yes

- name: Extract the Go tarball
  unarchive:
    src: "{{dir}}/go{{go_version}}.linux-amd64.tar.gz"
    dest: /usr/local
    copy: no

- name: create go directories in home
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - "{{dir}}/go"
    - "{{dir}}/go/bin"

- name: modify .bashrc
  blockinfile:
    dest: "{{dir}}/.bashrc"
    block: |
      export GOPATH=$HOME/go
      export GOBIN=$GOPATH/bin
      export PATH=$GOBIN:$PATH:/usr/local/go/bin
    marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
    insertafter: EOF
    create: yes